env: standard

runtime: nodejs16

instance_class: F1

service: nextjs

handlers:
  - url: /.*
    script: auto
    secure: always

env_variables:
  NODE_ENV: "production"

automatic_scaling:
  min_instances: 0 # 動かしてないときはインスタンスを0にする
  max_instances: 1